### ISSUE TITLE
Just a Question: Why did you use an array to store your Service Mapping ?

### ISSUE THREAD

**Issue by tom-biebl** [mrcwbr/ioc-service-container#9]
Hello there,

I took a look at your source code and wondered, why you use an array to store the service-mapping instead of an Map ?

That's not a condemnation, I'm just wondering.
I am looking forward to hear from you.

Tom

**Comment by mrcwbr** [comment]
hey nice hint. I just create a PR where I change the implementation to an object. it should also increase the performance of the service container: https://github.com/mrcwbr/ioc-service-container/pull/10 if you like the code, I'll close the PR and publish a new release.

**Comment by tom-biebl** [comment]
Yeah looks nice, i am looking forward to check out the new performance :) 

Have a great day mate!
